source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Firebase as database
gem 'firebase'
# Use GeoHash to interact with GeoFire
gem 'c_geohash', require: 'geohash'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# Use Bootstrap for eye candy
gem 'bootstrap-sass', '~> 3.2.0'
gem 'autoprefixer-rails'
# See https://github.com/rails/execjs#readme for more supported runtimes
#gem 'therubyracer', platforms: :ruby
#Simple, efficient background processing for Ruby
gem "sidekiq"
gem 'whenever', :require => false
gem 'responders', '~> 2.0'

#Pure Ruby gem that implements the MQTT protocol
gem 'mqtt'

gem 'figaro'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'jquery-turbolinks'
# Makes http fun again!
gem 'httparty'
# adds pagination to ActiveModels
# Nokogiri is an HTML, XML, SAX, and Reader parser. 
gem 'nokogiri', '~> 1.6.6.2'
gem 'kaminari'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'bower-rails'

gem 'angular-rails-templates'

gem 'sprockets', '2.12.3'


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app servee
# gem 'unicorn'

# Use Capistrano for deployment
gem 'capistrano-rails', group: :development
gem 'capistrano-passenger', group: :development
gem 'capistrano-bundler', '~> 1.1.2', group: :development
gem 'capistrano-bower', group: :development
gem 'capistrano-sidekiq', group: :development

# Enable if U really need it...
#gem 'travis', '~> 1.7.6', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'launchy'
  gem 'webmock'
  gem 'selenium-webdriver'
end

group :development do
  gem 'therubyracer', platforms: :ruby
end

