---
:concurrency: 25
:sidekiq_pid => File.join(shared_path, 'tmp', 'pids', 'sidekiq.pid')
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - [critical, 3]
  - [default, 2]
  - [low, 1]